/*!
* \file   TFEL/Material/NonAssociativeDruckerPragerBehaviourData.hxx
* \brief  this file implements the NonAssociativeDruckerPragerBehaviourData class.
*         File generated by tfel version 4.0.0-dev
* \author Thomas Helfer ( modified by Caiua )
 */

#ifndef LIB_TFELMATERIAL_NONASSOCIATIVEDRUCKERPRAGER_BEHAVIOUR_DATA_HXX
#define LIB_TFELMATERIAL_NONASSOCIATIVEDRUCKERPRAGER_BEHAVIOUR_DATA_HXX

#include<limits>
#include<string>
#include<sstream>
#include<iostream>
#include<stdexcept>
#include<algorithm>

#include"TFEL/Raise.hxx"
#include"TFEL/PhysicalConstants.hxx"
#include"TFEL/Config/TFELConfig.hxx"
#include"TFEL/Config/TFELTypes.hxx"
#include"TFEL/TypeTraits/IsFundamentalNumericType.hxx"
#include"TFEL/TypeTraits/IsReal.hxx"
#include"TFEL/Math/General/Abs.hxx"
#include"TFEL/Math/General/IEEE754.hxx"
#include"TFEL/Math/Array/ViewsArrayIO.hxx"
#include"TFEL/Math/Array/fsarrayIO.hxx"
#include"TFEL/Math/Array/runtime_arrayIO.hxx"
#include"TFEL/Math/fsarray.hxx"
#include"TFEL/Math/runtime_array.hxx"
#include"TFEL/Math/stensor.hxx"
#include"TFEL/Math/Stensor/StensorConceptIO.hxx"
#include"TFEL/Math/tmatrix.hxx"
#include"TFEL/Math/Matrix/tmatrixIO.hxx"
#include"TFEL/Math/st2tost2.hxx"
#include"TFEL/Math/ST2toST2/ST2toST2ConceptIO.hxx"
#include"TFEL/Material/ModellingHypothesis.hxx"

#include "MFront/GenericBehaviour/State.hxx"
#include "MFront/GenericBehaviour/BehaviourData.hxx"
namespace tfel::material{

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis,typename,bool>
class NonAssociativeDruckerPragerBehaviourData;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType,bool use_qt>
class NonAssociativeDruckerPragerIntegrationData;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis,typename NumericType>
std::ostream&
 operator <<(std::ostream&,const NonAssociativeDruckerPragerBehaviourData<hypothesis, NumericType,false>&);

//! \brief forward declaration
template<typename NumericType>
std::ostream&
 operator <<(std::ostream&,const NonAssociativeDruckerPragerBehaviourData<ModellingHypothesis::AXISYMMETRICALGENERALISEDPLANESTRESS, NumericType, false>&);

//! \brief forward declaration
template<typename NumericType>
std::ostream&
 operator <<(std::ostream&,const NonAssociativeDruckerPragerBehaviourData<ModellingHypothesis::PLANESTRESS, NumericType, false>&);

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
class NonAssociativeDruckerPragerBehaviourData<hypothesis, NumericType,false>
{

static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const NonAssociativeDruckerPragerBehaviourData&);

/* integration data is declared friend to access   driving variables at the beginning of the time step */
friend class NonAssociativeDruckerPragerIntegrationData<hypothesis, NumericType, false>;

static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = StiffnessTensor;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

protected:

StrainStensor eto;

StressStensor sig;

#line 17 "NonAssociativeDruckerPrager.mfront"
stress young;
#line 20 "NonAssociativeDruckerPrager.mfront"
real nu;
#line 23 "NonAssociativeDruckerPrager.mfront"
real d;
#line 25 "NonAssociativeDruckerPrager.mfront"
real beta;
#line 27 "NonAssociativeDruckerPrager.mfront"
real phi;

StrainStensor eel;
#line 29 "NonAssociativeDruckerPrager.mfront"
strain p;
temperature T;

public:

/*!
* \brief Default constructor
*/
NonAssociativeDruckerPragerBehaviourData()
{}

/*!
* \brief copy constructor
*/
NonAssociativeDruckerPragerBehaviourData(const NonAssociativeDruckerPragerBehaviourData& src)
: eto(src.eto),
sig(src.sig),
young(src.young),
nu(src.nu),
d(src.d),
beta(src.beta),
phi(src.phi),
eel(src.eel),
p(src.p),
T(src.T)
{}

/*
 * \brief constructor for the Generic interface
 * \param[in] mgb_d: behaviour data
 */
NonAssociativeDruckerPragerBehaviourData(const mfront::gb::BehaviourData& mgb_d)
: young(mgb_d.s1.material_properties[0u]),
nu(mgb_d.s1.material_properties[1]),
d(mgb_d.s1.material_properties[2]),
beta(mgb_d.s1.material_properties[3]),
phi(mgb_d.s1.material_properties[4]),
eel(&mgb_d.s0.internal_state_variables[0u]),
p(mgb_d.s0.internal_state_variables[StensorSize]),
T(mgb_d.s0.external_state_variables[0u])
{
}


/*
* \brief Assignement operator
*/
NonAssociativeDruckerPragerBehaviourData&
operator=(const NonAssociativeDruckerPragerBehaviourData& src){
this->eto = src.eto;
this->sig = src.sig;
this->young = src.young;
this->nu = src.nu;
this->d = src.d;
this->beta = src.beta;
this->phi = src.phi;
this->eel = src.eel;
this->p = src.p;
this->T = src.T;
return *this;
}

void exportStateData(mfront::gb::State& mbg_s1) const
{
using namespace tfel::math;
tfel::math::map<StressStensor>(mbg_s1.thermodynamic_forces) = this->sig;
tfel::math::map<StrainStensor>(mbg_s1.internal_state_variables) = this->eel;
mbg_s1.internal_state_variables[StensorSize] = this->p;
} // end of exportStateData

}; // end of NonAssociativeDruckerPragerBehaviourDataclass

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
operator <<(std::ostream& os,const NonAssociativeDruckerPragerBehaviourData<hypothesis, NumericType, false>& b)
{
os << "εᵗᵒ : " << b.eto << '\n';
os << "σ : " << b.sig << '\n';
os << "young : " << b.young << '\n';
os << "nu : " << b.nu << '\n';
os << "d : " << b.d << '\n';
os << "beta : " << b.beta << '\n';
os << "phi : " << b.phi << '\n';
os << "εᵉˡ : " << b.eel << '\n';
os << "p : " << b.p << '\n';
os << "T : " << b.T << '\n';
return os;
}

template<typename NumericType>
class NonAssociativeDruckerPragerBehaviourData<ModellingHypothesis::AXISYMMETRICALGENERALISEDPLANESTRESS, NumericType, false>
{

static constexpr ModellingHypothesis::Hypothesis hypothesis = ModellingHypothesis::AXISYMMETRICALGENERALISEDPLANESTRESS;
static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const NonAssociativeDruckerPragerBehaviourData&);

/* integration data is declared friend to access   driving variables at the beginning of the time step */
friend class NonAssociativeDruckerPragerIntegrationData<hypothesis, NumericType, false>;

static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = StiffnessTensor;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

protected:

StrainStensor eto;

StressStensor sig;

#line 17 "NonAssociativeDruckerPrager.mfront"
stress young;
#line 20 "NonAssociativeDruckerPrager.mfront"
real nu;
#line 23 "NonAssociativeDruckerPrager.mfront"
real d;
#line 25 "NonAssociativeDruckerPrager.mfront"
real beta;
#line 27 "NonAssociativeDruckerPrager.mfront"
real phi;

StrainStensor eel;
#line 29 "NonAssociativeDruckerPrager.mfront"
strain p;
strain etozz;
temperature T;
strain sigzz;

public:

/*!
* \brief Default constructor
*/
NonAssociativeDruckerPragerBehaviourData()
{}

/*!
* \brief copy constructor
*/
NonAssociativeDruckerPragerBehaviourData(const NonAssociativeDruckerPragerBehaviourData& src)
: eto(src.eto),
sig(src.sig),
young(src.young),
nu(src.nu),
d(src.d),
beta(src.beta),
phi(src.phi),
eel(src.eel),
p(src.p),
etozz(src.etozz),
T(src.T),
sigzz(src.sigzz)
{}

/*
 * \brief constructor for the Generic interface
 * \param[in] mgb_d: behaviour data
 */
NonAssociativeDruckerPragerBehaviourData(const mfront::gb::BehaviourData& mgb_d)
: young(mgb_d.s1.material_properties[0u]),
nu(mgb_d.s1.material_properties[1]),
d(mgb_d.s1.material_properties[2]),
beta(mgb_d.s1.material_properties[3]),
phi(mgb_d.s1.material_properties[4]),
eel(&mgb_d.s0.internal_state_variables[0u]),
p(mgb_d.s0.internal_state_variables[StensorSize]),
etozz(mgb_d.s0.internal_state_variables[1 + StensorSize]),
T(mgb_d.s0.external_state_variables[0u]),
sigzz(mgb_d.s0.external_state_variables[1])
{
}


/*
* \brief Assignement operator
*/
NonAssociativeDruckerPragerBehaviourData&
operator=(const NonAssociativeDruckerPragerBehaviourData& src){
this->eto = src.eto;
this->sig = src.sig;
this->young = src.young;
this->nu = src.nu;
this->d = src.d;
this->beta = src.beta;
this->phi = src.phi;
this->eel = src.eel;
this->p = src.p;
this->etozz = src.etozz;
this->T = src.T;
this->sigzz = src.sigzz;
return *this;
}

void exportStateData(mfront::gb::State& mbg_s1) const
{
using namespace tfel::math;
tfel::math::map<StressStensor>(mbg_s1.thermodynamic_forces) = this->sig;
tfel::math::map<StrainStensor>(mbg_s1.internal_state_variables) = this->eel;
mbg_s1.internal_state_variables[StensorSize] = this->p;
mbg_s1.internal_state_variables[1 + StensorSize] = this->etozz;
} // end of exportStateData

}; // end of NonAssociativeDruckerPragerBehaviourDataclass

template<typename NumericType>
std::ostream&
operator <<(std::ostream& os,const NonAssociativeDruckerPragerBehaviourData<ModellingHypothesis::AXISYMMETRICALGENERALISEDPLANESTRESS, NumericType, false>& b)
{
os << "εᵗᵒ : " << b.eto << '\n';
os << "σ : " << b.sig << '\n';
os << "young : " << b.young << '\n';
os << "nu : " << b.nu << '\n';
os << "d : " << b.d << '\n';
os << "beta : " << b.beta << '\n';
os << "phi : " << b.phi << '\n';
os << "εᵉˡ : " << b.eel << '\n';
os << "p : " << b.p << '\n';
os << "etozz : " << b.etozz << '\n';
os << "T : " << b.T << '\n';
os << "sigzz : " << b.sigzz << '\n';
return os;
}

template<typename NumericType>
class NonAssociativeDruckerPragerBehaviourData<ModellingHypothesis::PLANESTRESS, NumericType, false>
{

static constexpr ModellingHypothesis::Hypothesis hypothesis = ModellingHypothesis::PLANESTRESS;
static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const NonAssociativeDruckerPragerBehaviourData&);

/* integration data is declared friend to access   driving variables at the beginning of the time step */
friend class NonAssociativeDruckerPragerIntegrationData<hypothesis, NumericType, false>;

static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = StiffnessTensor;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

protected:

StrainStensor eto;

StressStensor sig;

#line 17 "NonAssociativeDruckerPrager.mfront"
stress young;
#line 20 "NonAssociativeDruckerPrager.mfront"
real nu;
#line 23 "NonAssociativeDruckerPrager.mfront"
real d;
#line 25 "NonAssociativeDruckerPrager.mfront"
real beta;
#line 27 "NonAssociativeDruckerPrager.mfront"
real phi;

StrainStensor eel;
#line 29 "NonAssociativeDruckerPrager.mfront"
strain p;
strain etozz;
temperature T;

public:

/*!
* \brief Default constructor
*/
NonAssociativeDruckerPragerBehaviourData()
{}

/*!
* \brief copy constructor
*/
NonAssociativeDruckerPragerBehaviourData(const NonAssociativeDruckerPragerBehaviourData& src)
: eto(src.eto),
sig(src.sig),
young(src.young),
nu(src.nu),
d(src.d),
beta(src.beta),
phi(src.phi),
eel(src.eel),
p(src.p),
etozz(src.etozz),
T(src.T)
{}

/*
 * \brief constructor for the Generic interface
 * \param[in] mgb_d: behaviour data
 */
NonAssociativeDruckerPragerBehaviourData(const mfront::gb::BehaviourData& mgb_d)
: young(mgb_d.s1.material_properties[0u]),
nu(mgb_d.s1.material_properties[1]),
d(mgb_d.s1.material_properties[2]),
beta(mgb_d.s1.material_properties[3]),
phi(mgb_d.s1.material_properties[4]),
eel(&mgb_d.s0.internal_state_variables[0u]),
p(mgb_d.s0.internal_state_variables[StensorSize]),
etozz(mgb_d.s0.internal_state_variables[1 + StensorSize]),
T(mgb_d.s0.external_state_variables[0u])
{
}


/*
* \brief Assignement operator
*/
NonAssociativeDruckerPragerBehaviourData&
operator=(const NonAssociativeDruckerPragerBehaviourData& src){
this->eto = src.eto;
this->sig = src.sig;
this->young = src.young;
this->nu = src.nu;
this->d = src.d;
this->beta = src.beta;
this->phi = src.phi;
this->eel = src.eel;
this->p = src.p;
this->etozz = src.etozz;
this->T = src.T;
return *this;
}

void exportStateData(mfront::gb::State& mbg_s1) const
{
using namespace tfel::math;
tfel::math::map<StressStensor>(mbg_s1.thermodynamic_forces) = this->sig;
tfel::math::map<StrainStensor>(mbg_s1.internal_state_variables) = this->eel;
mbg_s1.internal_state_variables[StensorSize] = this->p;
mbg_s1.internal_state_variables[1 + StensorSize] = this->etozz;
} // end of exportStateData

}; // end of NonAssociativeDruckerPragerBehaviourDataclass

template<typename NumericType>
std::ostream&
operator <<(std::ostream& os,const NonAssociativeDruckerPragerBehaviourData<ModellingHypothesis::PLANESTRESS, NumericType, false>& b)
{
os << "εᵗᵒ : " << b.eto << '\n';
os << "σ : " << b.sig << '\n';
os << "young : " << b.young << '\n';
os << "nu : " << b.nu << '\n';
os << "d : " << b.d << '\n';
os << "beta : " << b.beta << '\n';
os << "phi : " << b.phi << '\n';
os << "εᵉˡ : " << b.eel << '\n';
os << "p : " << b.p << '\n';
os << "etozz : " << b.etozz << '\n';
os << "T : " << b.T << '\n';
return os;
}

} // end of namespace tfel::material

#endif /* LIB_TFELMATERIAL_NONASSOCIATIVEDRUCKERPRAGER_BEHAVIOUR_DATA_HXX */
