/*!
* \file   ImplicitNorton.cxx
* \brief  this file implements the ImplicitNorton Behaviour.
*         File generated by tfel version 4.0.0-dev
* \author Thomas Helfer - modified
* \date   24 / 11 / 2016
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/ImplicitNortonBehaviourData.hxx"
#include"TFEL/Material/ImplicitNortonIntegrationData.hxx"
#include"TFEL/Material/ImplicitNorton.hxx"

namespace tfel::material{

ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer&
ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::get()
{
static ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer i;
return i;
}

ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer()
{
// Reading parameters from a file
ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters(*this,"ImplicitNorton-parameters.txt");
ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters(*this,"ImplicitNortonAxisymmetricalGeneralisedPlaneStress-parameters.txt");
}

void
ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("RelativeValueForTheEquivalentStressLowerBoundDefinition",key)==0){
ImplicitNortonParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",v);
} else if(::strcmp("epsilon",key)==0){
ImplicitNortonParametersInitializer::get().set("epsilon",v);
} else if(::strcmp("theta",key)==0){
ImplicitNortonParametersInitializer::get().set("theta",v);
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
ImplicitNortonParametersInitializer::get().set("minimal_time_step_scaling_factor",v);
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
ImplicitNortonParametersInitializer::get().set("maximal_time_step_scaling_factor",v);
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
ImplicitNortonParametersInitializer::get().set("numerical_jacobian_epsilon",v);
} else {
tfel::raise("ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
ImplicitNortonParametersInitializer::get().set("iterMax",v);
} else {
tfel::raise("ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

void
ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters(ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer&,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"ImplicitNortonAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("RelativeValueForTheEquivalentStressLowerBoundDefinition"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("epsilon"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("epsilon",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("theta"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("theta",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("minimal_time_step_scaling_factor"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("minimal_time_step_scaling_factor",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("maximal_time_step_scaling_factor"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("maximal_time_step_scaling_factor",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("numerical_jacobian_epsilon"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("numerical_jacobian_epsilon",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("iterMax"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("iterMax",
ImplicitNortonParametersInitializer::getUnsignedShort(tokens[0],tokens[1]));
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

ImplicitNortonPlaneStressParametersInitializer&
ImplicitNortonPlaneStressParametersInitializer::get()
{
static ImplicitNortonPlaneStressParametersInitializer i;
return i;
}

ImplicitNortonPlaneStressParametersInitializer::ImplicitNortonPlaneStressParametersInitializer()
{
// Reading parameters from a file
ImplicitNortonPlaneStressParametersInitializer::readParameters(*this,"ImplicitNorton-parameters.txt");
ImplicitNortonPlaneStressParametersInitializer::readParameters(*this,"ImplicitNortonPlaneStress-parameters.txt");
}

void
ImplicitNortonPlaneStressParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("RelativeValueForTheEquivalentStressLowerBoundDefinition",key)==0){
ImplicitNortonParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",v);
} else if(::strcmp("epsilon",key)==0){
ImplicitNortonParametersInitializer::get().set("epsilon",v);
} else if(::strcmp("theta",key)==0){
ImplicitNortonParametersInitializer::get().set("theta",v);
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
ImplicitNortonParametersInitializer::get().set("minimal_time_step_scaling_factor",v);
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
ImplicitNortonParametersInitializer::get().set("maximal_time_step_scaling_factor",v);
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
ImplicitNortonParametersInitializer::get().set("numerical_jacobian_epsilon",v);
} else {
tfel::raise("ImplicitNortonPlaneStressParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
ImplicitNortonPlaneStressParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
ImplicitNortonParametersInitializer::get().set("iterMax",v);
} else {
tfel::raise("ImplicitNortonPlaneStressParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

void
ImplicitNortonPlaneStressParametersInitializer::readParameters(ImplicitNortonPlaneStressParametersInitializer&,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"ImplicitNortonPlaneStressParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("RelativeValueForTheEquivalentStressLowerBoundDefinition"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("epsilon"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("epsilon",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("theta"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("theta",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("minimal_time_step_scaling_factor"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("minimal_time_step_scaling_factor",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("maximal_time_step_scaling_factor"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("maximal_time_step_scaling_factor",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("numerical_jacobian_epsilon"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("numerical_jacobian_epsilon",
ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("iterMax"==tokens[0]){
ImplicitNortonParametersInitializer::get().set("iterMax",
ImplicitNortonParametersInitializer::getUnsignedShort(tokens[0],tokens[1]));
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

ImplicitNortonParametersInitializer&
ImplicitNortonParametersInitializer::get()
{
static ImplicitNortonParametersInitializer i;
return i;
}

ImplicitNortonParametersInitializer::ImplicitNortonParametersInitializer()
{
this->relative_value_for_the_equivalent_stress_lower_bound = 1e-12;
this->epsilon = 1e-16;
this->theta = 1;
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.7976931348623e+308;
this->numerical_jacobian_epsilon = 1e-17;
this->iterMax = 100;
// Reading parameters from a file
ImplicitNortonParametersInitializer::readParameters(*this,"ImplicitNorton-parameters.txt");
}

void
ImplicitNortonParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("RelativeValueForTheEquivalentStressLowerBoundDefinition",key)==0){
this->relative_value_for_the_equivalent_stress_lower_bound = v;
} else if(::strcmp("epsilon",key)==0){
this->epsilon = v;
} else if(::strcmp("theta",key)==0){
this->theta = v;
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
this->numerical_jacobian_epsilon = v;
} else {
tfel::raise("ImplicitNortonParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
ImplicitNortonParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
this->iterMax = v;
} else {
tfel::raise("ImplicitNortonParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

double
ImplicitNortonParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"ImplicitNortonParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

unsigned short
ImplicitNortonParametersInitializer::getUnsignedShort(const std::string& n,
const std::string& v)
{
unsigned short value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"ImplicitNortonParametersInitializer::getUnsignedShort: "
"can't convert '"+v+"' to unsigned short for parameter '"+ n+"'");
return value;
}

void
ImplicitNortonParametersInitializer::readParameters(ImplicitNortonParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"ImplicitNortonParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("RelativeValueForTheEquivalentStressLowerBoundDefinition"==tokens[0]){
pi.relative_value_for_the_equivalent_stress_lower_bound = ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("epsilon"==tokens[0]){
pi.epsilon = ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("theta"==tokens[0]){
pi.theta = ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("numerical_jacobian_epsilon"==tokens[0]){
pi.numerical_jacobian_epsilon = ImplicitNortonParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("iterMax"==tokens[0]){
pi.iterMax = ImplicitNortonParametersInitializer::getUnsignedShort(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace tfel::material

