/*!
* \file   LinearElasticity.cxx
* \brief  this file implements the LinearElasticity Behaviour.
*         File generated by tfel version 4.0.0-dev
* \author Helfer Thomas
* \date   23 / 11 / 06
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/LinearElasticityBehaviourData.hxx"
#include"TFEL/Material/LinearElasticityIntegrationData.hxx"
#include"TFEL/Material/LinearElasticity.hxx"

namespace tfel::material{

LinearElasticityParametersInitializer&
LinearElasticityParametersInitializer::get()
{
static LinearElasticityParametersInitializer i;
return i;
}

LinearElasticityParametersInitializer::LinearElasticityParametersInitializer()
{
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.7976931348623e+308;
// Reading parameters from a file
LinearElasticityParametersInitializer::readParameters(*this,"LinearElasticity-parameters.txt");
}

void
LinearElasticityParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else {
tfel::raise("LinearElasticityParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

double
LinearElasticityParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"LinearElasticityParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

void
LinearElasticityParametersInitializer::readParameters(LinearElasticityParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"LinearElasticityParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = LinearElasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = LinearElasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace tfel::material

