/*!
* \file   NonAssociativeDruckerPrager.cxx
* \brief  this file implements the NonAssociativeDruckerPrager Behaviour.
*         File generated by tfel version 4.0.0-dev
* \author Thomas Helfer ( modified by Caiua )
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/NonAssociativeDruckerPragerBehaviourData.hxx"
#include"TFEL/Material/NonAssociativeDruckerPragerIntegrationData.hxx"
#include"TFEL/Material/NonAssociativeDruckerPrager.hxx"

namespace tfel::material{

NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer&
NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::get()
{
static NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer i;
return i;
}

NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer()
{
// Reading parameters from a file
NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters(*this,"NonAssociativeDruckerPrager-parameters.txt");
NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters(*this,"NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStress-parameters.txt");
}

void
NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("RelativeValueForTheEquivalentStressLowerBoundDefinition",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",v);
} else if(::strcmp("epsilon",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("epsilon",v);
} else if(::strcmp("theta",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("theta",v);
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("minimal_time_step_scaling_factor",v);
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("maximal_time_step_scaling_factor",v);
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("numerical_jacobian_epsilon",v);
} else {
tfel::raise("NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("iterMax",v);
} else {
tfel::raise("NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

void
NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters(NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer&,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"NonAssociativeDruckerPragerAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("RelativeValueForTheEquivalentStressLowerBoundDefinition"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("epsilon"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("epsilon",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("theta"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("theta",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("minimal_time_step_scaling_factor"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("minimal_time_step_scaling_factor",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("maximal_time_step_scaling_factor"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("maximal_time_step_scaling_factor",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("numerical_jacobian_epsilon"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("numerical_jacobian_epsilon",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("iterMax"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("iterMax",
NonAssociativeDruckerPragerParametersInitializer::getUnsignedShort(tokens[0],tokens[1]));
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

NonAssociativeDruckerPragerPlaneStressParametersInitializer&
NonAssociativeDruckerPragerPlaneStressParametersInitializer::get()
{
static NonAssociativeDruckerPragerPlaneStressParametersInitializer i;
return i;
}

NonAssociativeDruckerPragerPlaneStressParametersInitializer::NonAssociativeDruckerPragerPlaneStressParametersInitializer()
{
// Reading parameters from a file
NonAssociativeDruckerPragerPlaneStressParametersInitializer::readParameters(*this,"NonAssociativeDruckerPrager-parameters.txt");
NonAssociativeDruckerPragerPlaneStressParametersInitializer::readParameters(*this,"NonAssociativeDruckerPragerPlaneStress-parameters.txt");
}

void
NonAssociativeDruckerPragerPlaneStressParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("RelativeValueForTheEquivalentStressLowerBoundDefinition",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",v);
} else if(::strcmp("epsilon",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("epsilon",v);
} else if(::strcmp("theta",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("theta",v);
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("minimal_time_step_scaling_factor",v);
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("maximal_time_step_scaling_factor",v);
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("numerical_jacobian_epsilon",v);
} else {
tfel::raise("NonAssociativeDruckerPragerPlaneStressParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
NonAssociativeDruckerPragerPlaneStressParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
NonAssociativeDruckerPragerParametersInitializer::get().set("iterMax",v);
} else {
tfel::raise("NonAssociativeDruckerPragerPlaneStressParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

void
NonAssociativeDruckerPragerPlaneStressParametersInitializer::readParameters(NonAssociativeDruckerPragerPlaneStressParametersInitializer&,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"NonAssociativeDruckerPragerPlaneStressParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("RelativeValueForTheEquivalentStressLowerBoundDefinition"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("epsilon"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("epsilon",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("theta"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("theta",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("minimal_time_step_scaling_factor"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("minimal_time_step_scaling_factor",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("maximal_time_step_scaling_factor"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("maximal_time_step_scaling_factor",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("numerical_jacobian_epsilon"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("numerical_jacobian_epsilon",
NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("iterMax"==tokens[0]){
NonAssociativeDruckerPragerParametersInitializer::get().set("iterMax",
NonAssociativeDruckerPragerParametersInitializer::getUnsignedShort(tokens[0],tokens[1]));
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

NonAssociativeDruckerPragerParametersInitializer&
NonAssociativeDruckerPragerParametersInitializer::get()
{
static NonAssociativeDruckerPragerParametersInitializer i;
return i;
}

NonAssociativeDruckerPragerParametersInitializer::NonAssociativeDruckerPragerParametersInitializer()
{
this->relative_value_for_the_equivalent_stress_lower_bound = 1e-12;
this->epsilon = 1e-16;
this->theta = 1;
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.7976931348623e+308;
this->numerical_jacobian_epsilon = 1e-17;
this->iterMax = 100;
// Reading parameters from a file
NonAssociativeDruckerPragerParametersInitializer::readParameters(*this,"NonAssociativeDruckerPrager-parameters.txt");
}

void
NonAssociativeDruckerPragerParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("RelativeValueForTheEquivalentStressLowerBoundDefinition",key)==0){
this->relative_value_for_the_equivalent_stress_lower_bound = v;
} else if(::strcmp("epsilon",key)==0){
this->epsilon = v;
} else if(::strcmp("theta",key)==0){
this->theta = v;
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
this->numerical_jacobian_epsilon = v;
} else {
tfel::raise("NonAssociativeDruckerPragerParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
NonAssociativeDruckerPragerParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
this->iterMax = v;
} else {
tfel::raise("NonAssociativeDruckerPragerParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

double
NonAssociativeDruckerPragerParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"NonAssociativeDruckerPragerParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

unsigned short
NonAssociativeDruckerPragerParametersInitializer::getUnsignedShort(const std::string& n,
const std::string& v)
{
unsigned short value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"NonAssociativeDruckerPragerParametersInitializer::getUnsignedShort: "
"can't convert '"+v+"' to unsigned short for parameter '"+ n+"'");
return value;
}

void
NonAssociativeDruckerPragerParametersInitializer::readParameters(NonAssociativeDruckerPragerParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"NonAssociativeDruckerPragerParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("RelativeValueForTheEquivalentStressLowerBoundDefinition"==tokens[0]){
pi.relative_value_for_the_equivalent_stress_lower_bound = NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("epsilon"==tokens[0]){
pi.epsilon = NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("theta"==tokens[0]){
pi.theta = NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("numerical_jacobian_epsilon"==tokens[0]){
pi.numerical_jacobian_epsilon = NonAssociativeDruckerPragerParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("iterMax"==tokens[0]){
pi.iterMax = NonAssociativeDruckerPragerParametersInitializer::getUnsignedShort(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace tfel::material

