/*!
* \file   ViscoPlasticity.cxx
* \brief  this file implements the ViscoPlasticity Behaviour.
*         File generated by tfel version 4.0.0-dev
* \author Mauro Cacace ( GFZ Potsdam )
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/ViscoPlasticityBehaviourData.hxx"
#include"TFEL/Material/ViscoPlasticityIntegrationData.hxx"
#include"TFEL/Material/ViscoPlasticity.hxx"

namespace tfel::material{

ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer&
ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::get()
{
static ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer i;
return i;
}

ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer()
{
// Reading parameters from a file
ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters(*this,"ViscoPlasticity-parameters.txt");
ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters(*this,"ViscoPlasticityAxisymmetricalGeneralisedPlaneStress-parameters.txt");
}

void
ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("RelativeValueForTheEquivalentStressLowerBoundDefinition",key)==0){
ViscoPlasticityParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",v);
} else if(::strcmp("epsilon",key)==0){
ViscoPlasticityParametersInitializer::get().set("epsilon",v);
} else if(::strcmp("theta",key)==0){
ViscoPlasticityParametersInitializer::get().set("theta",v);
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
ViscoPlasticityParametersInitializer::get().set("minimal_time_step_scaling_factor",v);
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
ViscoPlasticityParametersInitializer::get().set("maximal_time_step_scaling_factor",v);
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
ViscoPlasticityParametersInitializer::get().set("numerical_jacobian_epsilon",v);
} else {
tfel::raise("ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
ViscoPlasticityParametersInitializer::get().set("iterMax",v);
} else {
tfel::raise("ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

void
ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters(ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer&,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"ViscoPlasticityAxisymmetricalGeneralisedPlaneStressParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("RelativeValueForTheEquivalentStressLowerBoundDefinition"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("epsilon"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("epsilon",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("theta"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("theta",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("minimal_time_step_scaling_factor"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("minimal_time_step_scaling_factor",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("maximal_time_step_scaling_factor"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("maximal_time_step_scaling_factor",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("numerical_jacobian_epsilon"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("numerical_jacobian_epsilon",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("iterMax"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("iterMax",
ViscoPlasticityParametersInitializer::getUnsignedShort(tokens[0],tokens[1]));
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

ViscoPlasticityPlaneStressParametersInitializer&
ViscoPlasticityPlaneStressParametersInitializer::get()
{
static ViscoPlasticityPlaneStressParametersInitializer i;
return i;
}

ViscoPlasticityPlaneStressParametersInitializer::ViscoPlasticityPlaneStressParametersInitializer()
{
// Reading parameters from a file
ViscoPlasticityPlaneStressParametersInitializer::readParameters(*this,"ViscoPlasticity-parameters.txt");
ViscoPlasticityPlaneStressParametersInitializer::readParameters(*this,"ViscoPlasticityPlaneStress-parameters.txt");
}

void
ViscoPlasticityPlaneStressParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("RelativeValueForTheEquivalentStressLowerBoundDefinition",key)==0){
ViscoPlasticityParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",v);
} else if(::strcmp("epsilon",key)==0){
ViscoPlasticityParametersInitializer::get().set("epsilon",v);
} else if(::strcmp("theta",key)==0){
ViscoPlasticityParametersInitializer::get().set("theta",v);
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
ViscoPlasticityParametersInitializer::get().set("minimal_time_step_scaling_factor",v);
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
ViscoPlasticityParametersInitializer::get().set("maximal_time_step_scaling_factor",v);
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
ViscoPlasticityParametersInitializer::get().set("numerical_jacobian_epsilon",v);
} else {
tfel::raise("ViscoPlasticityPlaneStressParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
ViscoPlasticityPlaneStressParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
ViscoPlasticityParametersInitializer::get().set("iterMax",v);
} else {
tfel::raise("ViscoPlasticityPlaneStressParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

void
ViscoPlasticityPlaneStressParametersInitializer::readParameters(ViscoPlasticityPlaneStressParametersInitializer&,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"ViscoPlasticityPlaneStressParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("RelativeValueForTheEquivalentStressLowerBoundDefinition"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("RelativeValueForTheEquivalentStressLowerBoundDefinition",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("epsilon"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("epsilon",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("theta"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("theta",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("minimal_time_step_scaling_factor"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("minimal_time_step_scaling_factor",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("maximal_time_step_scaling_factor"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("maximal_time_step_scaling_factor",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("numerical_jacobian_epsilon"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("numerical_jacobian_epsilon",
ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]));
} else if("iterMax"==tokens[0]){
ViscoPlasticityParametersInitializer::get().set("iterMax",
ViscoPlasticityParametersInitializer::getUnsignedShort(tokens[0],tokens[1]));
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

ViscoPlasticityParametersInitializer&
ViscoPlasticityParametersInitializer::get()
{
static ViscoPlasticityParametersInitializer i;
return i;
}

ViscoPlasticityParametersInitializer::ViscoPlasticityParametersInitializer()
{
this->relative_value_for_the_equivalent_stress_lower_bound = 1e-12;
this->epsilon = 1e-14;
this->theta = 1;
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.7976931348623e+308;
this->numerical_jacobian_epsilon = 1e-15;
this->iterMax = 100;
// Reading parameters from a file
ViscoPlasticityParametersInitializer::readParameters(*this,"ViscoPlasticity-parameters.txt");
}

void
ViscoPlasticityParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("RelativeValueForTheEquivalentStressLowerBoundDefinition",key)==0){
this->relative_value_for_the_equivalent_stress_lower_bound = v;
} else if(::strcmp("epsilon",key)==0){
this->epsilon = v;
} else if(::strcmp("theta",key)==0){
this->theta = v;
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
this->numerical_jacobian_epsilon = v;
} else {
tfel::raise("ViscoPlasticityParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
ViscoPlasticityParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
this->iterMax = v;
} else {
tfel::raise("ViscoPlasticityParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

double
ViscoPlasticityParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"ViscoPlasticityParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

unsigned short
ViscoPlasticityParametersInitializer::getUnsignedShort(const std::string& n,
const std::string& v)
{
unsigned short value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"ViscoPlasticityParametersInitializer::getUnsignedShort: "
"can't convert '"+v+"' to unsigned short for parameter '"+ n+"'");
return value;
}

void
ViscoPlasticityParametersInitializer::readParameters(ViscoPlasticityParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"ViscoPlasticityParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("RelativeValueForTheEquivalentStressLowerBoundDefinition"==tokens[0]){
pi.relative_value_for_the_equivalent_stress_lower_bound = ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("epsilon"==tokens[0]){
pi.epsilon = ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("theta"==tokens[0]){
pi.theta = ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("numerical_jacobian_epsilon"==tokens[0]){
pi.numerical_jacobian_epsilon = ViscoPlasticityParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("iterMax"==tokens[0]){
pi.iterMax = ViscoPlasticityParametersInitializer::getUnsignedShort(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace tfel::material

